//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_YCGL_CAR
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string CarNum { get; set; }
        public string CarType { get; set; }
        public string CarBrand { get; set; }
        public string CarXH { get; set; }
        public string Files { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string DelUser { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string BuyDate { get; set; }
        public string Price { get; set; }
        public string FDJNum { get; set; }
        public string SeatNum { get; set; }
        public string Remark { get; set; }
    }
}
