//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_HYGL_QR
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public Nullable<int> HYID { get; set; }
        public string QRUser { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string DelUser { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
    }
}
