//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_KQBC
    {
        public int ID { get; set; }
        public string KQTitle { get; set; }
        public string KQStart { get; set; }
        public string KQEnd { get; set; }
        public Nullable<System.DateTime> KQZXDate { get; set; }
        public string KQUsers { get; set; }
        public string KQWeekDay { get; set; }
        public Nullable<int> ComID { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string KQAddress { get; set; }
        public Nullable<int> KQRange { get; set; }
    }
}
