//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_JFBXITEM
    {
        public string ShenQingRen { get; set; }
        public string LeiBie { get; set; }
        public Nullable<System.DateTime> BXDate { get; set; }
        public string BXContent { get; set; }
        public Nullable<decimal> BXJE { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string BXDNum { get; set; }
        public string Remark { get; set; }
        public int ID { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<int> JFBXID { get; set; }
        public Nullable<int> IsHasFP { get; set; }
    }
}
