//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_CRM_HTGL
    {
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<System.DateTime> HTEndTime { get; set; }
        public string HTStatus { get; set; }
        public string HTCode { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> HTType { get; set; }
        public Nullable<int> FKFS { get; set; }
        public string KHQYR { get; set; }
        public string WFQYR { get; set; }
        public Nullable<System.DateTime> QYDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> HTStartTime { get; set; }
        public string Price { get; set; }
        public string DYSJ { get; set; }
        public Nullable<int> KHID { get; set; }
        public string Title { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string Files { get; set; }
        public string ExpiryDate { get; set; }
        public string FKSM { get; set; }
        public string FZR { get; set; }
    }
}
