//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_RWGL
    {
        public string RWContent { get; set; }
        public string RWTitle { get; set; }
        public string LeiBie { get; set; }
        public string RWJZDate { get; set; }
        public string RWFZR { get; set; }
        public string RWCYR { get; set; }
        public string RWStatus { get; set; }
        public string BiaoQian { get; set; }
        public string BeiZhu { get; set; }
        public string IsSend { get; set; }
        public string IsComPlete { get; set; }
        public string IsCancel { get; set; }
        public string CancelDate { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public string Remark { get; set; }
        public int ID { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public string KHFXRS { get; set; }
        public string CRUserName { get; set; }
        public Nullable<int> TopID { get; set; }
        public Nullable<int> ComId { get; set; }
        public string TaskJD { get; set; }
        public string IsTX { get; set; }
        public Nullable<int> XMID { get; set; }
    }
}
