//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_KQJL
    {
        public int ID { get; set; }
        public string KQUser { get; set; }
        public Nullable<System.DateTime> KQDate { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> WeekDay { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string KQUserName { get; set; }
        public string KQBranch { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Position { get; set; }
    }
}
