//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_CRM_KHGL
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string KHName { get; set; }
        public Nullable<int> KHType { get; set; }
        public string TelePhone { get; set; }
        public string FixNo { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string PostCode { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public string Lev { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> Industry { get; set; }
        public Nullable<int> Scale { get; set; }
        public string FZUser { get; set; }
        public string CYUser { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string Remark { get; set; }
        public string Files { get; set; }
        public string Attach1 { get; set; }
        public string Attach2 { get; set; }
    }
}
