//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_QYHDN
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string FQF { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> JZDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public Nullable<int> ComId { get; set; }
        public string CYR { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string HD_Content { get; set; }
        public string TP_IsNM { get; set; }
        public Nullable<int> TP_Type { get; set; }
        public string HD_Adress { get; set; }
        public Nullable<int> TP_IsPublic { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public string HDDate { get; set; }
    }
}
