//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_TSGL_TS
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string TSNum { get; set; }
        public string TSType { get; set; }
        public string TSTypeName { get; set; }
        public string TSXH { get; set; }
        public string Files { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string DelUser { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string BuyDate { get; set; }
        public string Price { get; set; }
        public string auther { get; set; }
        public string SL { get; set; }
        public string Remark { get; set; }
        public string TSName { get; set; }
        public string jystatus { get; set; }
        public string bc { get; set; }
        public string cbs { get; set; }
    }
}
