//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_QYHD_ITEM
    {
        public Nullable<int> BMCount { get; set; }
        public string BMLxDH { get; set; }
        public string BMLxr { get; set; }
        public Nullable<int> HDID { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public string Remark { get; set; }
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
    }
}
