//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_GZBG
    {
        public string BranchName { get; set; }
        public Nullable<int> LeiBie { get; set; }
        public Nullable<System.DateTime> RBDate { get; set; }
        public string RBJSR { get; set; }
        public string RBWCQK { get; set; }
        public string RBContent { get; set; }
        public string IsSend { get; set; }
        public string IsComPlete { get; set; }
        public string IsCancel { get; set; }
        public string CancelDate { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public string Remark { get; set; }
        public int ID { get; set; }
        public int intProcessStanceid { get; set; }
        public string CRUserName { get; set; }
        public Nullable<int> ComId { get; set; }
        public string ChaoSongUser { get; set; }
    }
}
