//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_TSGL
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string TSID { get; set; }
        public string TSName { get; set; }
        public string TSTypeName { get; set; }
        public string JYR { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Files { get; set; }
        public string JYRName { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public int intProcessStanceid { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string DelUser { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public Nullable<System.DateTime> BackDate { get; set; }
        public string BackBZ { get; set; }
    }
}
