//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_QYHD
    {
        public string HDTitle { get; set; }
        public string HDLeiBie { get; set; }
        public string HDPeople { get; set; }
        public string HDFQF { get; set; }
        public string isPublic { get; set; }
        public string isTX { get; set; }
        public Nullable<int> TXID { get; set; }
        public string HDAdress { get; set; }
        public Nullable<System.DateTime> HDTime { get; set; }
        public Nullable<System.DateTime> HDBMEndTime { get; set; }
        public string IsSend { get; set; }
        public string IsComPlete { get; set; }
        public string IsCancel { get; set; }
        public string CancelDate { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Files { get; set; }
        public string Remark { get; set; }
        public int ID { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public string HDContent { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<System.DateTime> HDEndTime { get; set; }
    }
}
