//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_HYGL
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CYUser { get; set; }
        public string FQUser { get; set; }
        public string JLUser { get; set; }
        public string ZCUser { get; set; }
        public string SXUser { get; set; }
        public string Desp { get; set; }
        public string Files { get; set; }
        public string IsTX { get; set; }
        public Nullable<int> TXSJ { get; set; }
        public string HYJL { get; set; }
        public string HYFW { get; set; }
        public string JLFiles { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public int intProcessStanceid { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string DelUser { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
    }
}
