//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_XMGL
    {
        public string XMMC { get; set; }
        public string XMMS { get; set; }
        public Nullable<decimal> XMJD { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string YXJ { get; set; }
        public string XMFZR { get; set; }
        public string XMCYR { get; set; }
        public string Files { get; set; }
        public int ID { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUserName { get; set; }
        public string Remark { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserName { get; set; }
        public int intProcessStanceid { get; set; }
        public Nullable<int> ComId { get; set; }
    }
}
