//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_RWGL_ITEM
    {
        public int ID { get; set; }
        public Nullable<int> RWID { get; set; }
        public string RWUSER { get; set; }
        public string RWTYPE { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RWSDate { get; set; }
        public Nullable<System.DateTime> RWEDate { get; set; }
        public Nullable<int> ComId { get; set; }
        public string RWWCQK { get; set; }
        public string RWDBR { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string Remark { get; set; }
        public string RWContent { get; set; }
        public string DBPJ { get; set; }
        public string RWBM { get; set; }
        public string RWTitle { get; set; }
        public string SHUser { get; set; }
        public Nullable<decimal> RWFS { get; set; }
        public string IsTX { get; set; }
    }
}
