//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_CRM_CONTACT
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public Nullable<int> KHID { get; set; }
        public string UserXM { get; set; }
        public string UserSex { get; set; }
        public string MobilePhone { get; set; }
        public string TelePhone { get; set; }
        public string Extension { get; set; }
        public string FixNo { get; set; }
        public string Education { get; set; }
        public string QQ { get; set; }
        public string Weixin { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string EMail { get; set; }
        public string Mailbox { get; set; }
        public string WebSite { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Others { get; set; }
        public string Remark { get; set; }
        public string Files { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
