//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_CRM_CPGL
    {
        public int ID { get; set; }
        public string PContent { get; set; }
        public string Name { get; set; }
        public string BianHao { get; set; }
        public string Price { get; set; }
        public string DanWei { get; set; }
        public string ChengBen { get; set; }
        public Nullable<int> LeiBie { get; set; }
        public string Files { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> ComId { get; set; }
    }
}
