//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_WQQD
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string Position { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string QDContent { get; set; }
        public byte[] KHName { get; set; }
        public string HBUser { get; set; }
        public string Files { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public string Remark { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUserName { get; set; }
    }
}
